# Generated by Django 5.2.6 on 2025-11-03 12:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('del_flag', models.SmallIntegerField(default=0, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('corporate_identification_number', models.CharField(max_length=21, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('date_of_incorporation', models.DateField()),
                ('place_of_incorporation', models.CharField(max_length=100)),
                ('state_of_incorporation', models.CharField(max_length=100)),
                ('entity_type', models.CharField(choices=[('PUBLIC_LTD', 'Public Ltd Company'), ('PRIVATE_LTD', 'Private Limited'), ('LLP', 'LLP'), ('PARTNERSHIP', 'Partnership Firm'), ('SOLE_PROP', 'Sole Proprietorship'), ('OPC', 'OPC'), ('TRUST_NGO', 'Trust/Society/NGO')], max_length=50)),
                ('company_or_individual_pan_card_file', models.FileField(blank=True, null=True, upload_to='company_documents/pan_cards/')),
                ('company_pan_number', models.CharField(max_length=10, unique=True)),
                ('pan_holder_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gstin', models.CharField(max_length=15)),
                ('msme_udyam_registration_no', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
                ('user_id_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to='authentication.user')),
            ],
            options={
                'db_table': 'company_kyc',
            },
        ),
        migrations.CreateModel(
            name='CompanyOnboardingApplication',
            fields=[
                ('del_flag', models.SmallIntegerField(default=0, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted for Review'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='INITIATED', max_length=20)),
                ('current_step', models.IntegerField(default=1)),
                ('step_completion', models.JSONField(blank=True, default=dict, help_text='Tracks completion status of each onboarding step.')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('company_information', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='issuer_kyc.companyinformation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_applications', to='authentication.user')),
                ('user_id_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to='authentication.user')),
            ],
            options={
                'db_table': 'company_onboarding_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('del_flag', models.SmallIntegerField(default=0, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('registered_office_address', models.TextField()),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state_ut', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=6)),
                ('country', models.CharField(default='India', max_length=100)),
                ('company_contact_email', models.EmailField(max_length=255)),
                ('company_contact_phone', models.CharField(max_length=15)),
                ('address_type', models.IntegerField(choices=[(0, 'REGISTERED'), (1, 'CORRESPONDENCE'), (2, 'BOTH')])),
                ('user_id_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to='authentication.user')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='issuer_kyc.companyinformation')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='issuer_kyc.companyonboardingapplication')),
            ],
            options={
                'db_table': 'company_address',
            },
        ),
        migrations.AddIndex(
            model_name='companyinformation',
            index=models.Index(fields=['user', 'del_flag'], name='company_kyc_user_id_341cde_idx'),
        ),
        migrations.AddIndex(
            model_name='companyinformation',
            index=models.Index(fields=['company_pan_number'], name='company_kyc_company_8eb3de_idx'),
        ),
        migrations.AddIndex(
            model_name='companyonboardingapplication',
            index=models.Index(fields=['user', 'status'], name='company_onb_user_id_0e5527_idx'),
        ),
        migrations.AddIndex(
            model_name='companyonboardingapplication',
            index=models.Index(fields=['current_step'], name='company_onb_current_262d67_idx'),
        ),
        migrations.AddIndex(
            model_name='companyaddress',
            index=models.Index(fields=['company', 'del_flag'], name='company_add_company_950567_idx'),
        ),
        migrations.AddIndex(
            model_name='companyaddress',
            index=models.Index(fields=['city', 'state_ut'], name='company_add_city_354b12_idx'),
        ),
    ]
