# Generated by Django 5.2.6 on 2025-11-20 05:41

import apps.kyc.issuer_kyc.models.CompanyDocumentModel

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('del_flag', models.SmallIntegerField(default=0, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('registered_office_address', models.TextField()),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state_ut', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=6)),
                ('country', models.CharField(default='India', max_length=100)),
                ('company_contact_email', models.EmailField(max_length=255)),
                ('company_contact_phone', models.CharField(max_length=15)),
                ('address_type', models.IntegerField(choices=[(0, 'REGISTERED'), (1, 'CORRESPONDENCE'), (2, 'BOTH')])),
                ('address_proof_file', models.FileField(blank=True, help_text='Path to the uploaded address proof document', null=True, upload_to='uploads/company_address/')),
            ],
            options={
                'db_table': 'company_address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyOnboardingApplication',
            fields=[
                ('del_flag', models.SmallIntegerField(default=0, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted for Review'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='INITIATED', max_length=20)),
                ('last_accessed_step', models.IntegerField(default=1, help_text='Last step user visited (analytics only)')),
                ('step_completion', models.JSONField(blank=True, default=dict, help_text='Tracks completion status of each onboarding step.')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'company_onboarding_applications',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DematAccount',
            fields=[
                ('del_flag', models.SmallIntegerField(default=0, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demat_account_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dp_name', models.CharField(max_length=50)),
                ('depository_participant', models.CharField(choices=[('NSDL', 'NSDL'), ('CDSL', 'CDSL')], max_length=10)),
                ('dp_id', models.CharField(max_length=20)),
                ('demat_account_number', models.CharField(max_length=50, unique=True)),
                ('client_id_bo_id', models.CharField(blank=True, max_length=20, null=True)),
                ('user_id_updated_by', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'demat_accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('del_flag', models.SmallIntegerField(default=0, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('human_intervention', models.BooleanField(help_text='Manual review required?')),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('SUCCESS', 'Verified Successfully'), ('FAILED', 'Failed Verification')], default='PENDING', max_length=20)),
                ('company_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('corporate_identification_number', models.CharField(max_length=21)),
                ('company_name', models.CharField(max_length=255)),
                ('gstin', models.CharField(max_length=15)),
                ('date_of_incorporation', models.DateField()),
                ('city_of_incorporation', models.CharField(max_length=100)),
                ('state_of_incorporation', models.CharField(max_length=100)),
                ('country_of_incorporation', models.CharField(max_length=100)),
                ('entity_type', models.CharField(choices=[('PUBLIC_LTD', 'Public Ltd Company'), ('PRIVATE_LTD', 'Private Limited'), ('LLP', 'LLP'), ('PARTNERSHIP', 'Partnership Firm'), ('SOLE_PROP', 'Sole Proprietorship'), ('OPC', 'OPC'), ('TRUST_NGO', 'Trust/Society/NGO')], max_length=50)),
                ('sector', models.CharField(choices=[('BANKING', 'banking'), ('INFRASTRUCTURE', 'Infrastructure'), ('POWER', 'Power'), ('REAL ESTATE', 'Real Estate'), ('MANUFACTURING', 'Manufacturing'), ('IT', 'IT & Software'), ('PUBLIC SECTOR UNDERTAKING', 'Public Sector Undertaking'), ('OTHERS', 'Others')], max_length=50)),
                ('company_or_individual_pan_card_file', models.FileField(upload_to='company_documents/pan_cards/')),
                ('company_pan_number', models.CharField(max_length=10)),
                ('pan_holder_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('msme_udyam_registration_no', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_id_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_kyc',
            },
        ),
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('del_flag', models.SmallIntegerField(default=0, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_name', models.CharField(choices=[('CERTIFICATE_INC', 'Certificate of Incorporation'), ('MOA', 'Memorandum of Association (MoA)'), ('AOA', 'Articles of Association (AoA)'), ('MSME', 'MSME Certificate'), ('UDYAM', 'Udyam Certificate'), ('IEC', 'Import Export Certificate (IEC)')], help_text='Select document type from dropdown', max_length=100)),
                ('document_type', models.CharField(choices=[('PDF', 'PDF'), ('JPEG', 'JPEG'), ('JPG', 'JPG'), ('PNG', 'PNG')], help_text='Auto-detected from file extension', max_length=10)),
                ('document_file', models.FileField(help_text='Document stored with company name folder structure', upload_to=apps.kyc.issuer_kyc.models.CompanyDocumentModel.company_document_upload_path)),
                ('file_size', models.IntegerField(help_text='File size in bytes for validation')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_mandatory', models.BooleanField(default=False, help_text='Auto-set based on document_name')),
                ('is_verified', models.BooleanField(default=False, help_text='Admin verification status')),
                ('user_id_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='issuer_kyc.companyinformation')),
            ],
            options={
                'db_table': 'company_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('del_flag', models.SmallIntegerField(default=0, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_detail_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cancelled_cheque', models.FileField(blank=True, null=True, upload_to='onboarding/bank/cancelled_cheques/')),
                ('bank_statement', models.FileField(blank=True, null=True, upload_to='onboarding/bank/statements/')),
                ('passbook', models.FileField(blank=True, null=True, upload_to='onboarding/bank/passbooks/')),
                ('bank_name', models.CharField(max_length=100)),
                ('branch_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=30)),
                ('account_type', models.CharField(choices=[('SAVINGS', 'Savings'), ('CURRENT', 'Current')], max_length=20)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(null=True)),
                ('verified_data_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('user_id_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='issuer_kyc.companyinformation')),
            ],
            options={
                'db_table': 'bank_details',
            },
        ),
        migrations.CreateModel(
            name='CompanySignatory',
            fields=[
                ('del_flag', models.SmallIntegerField(default=0, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signatory_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_of_signatory', models.CharField(max_length=255)),
                ('designation', models.CharField(choices=[('DIRECTOR', 'Director'), ('SIGNATORY', 'Signatory'), ('MANAGER', 'Manager')], max_length=50)),
                ('din', models.CharField(max_length=8)),
                ('pan_number', models.CharField(max_length=10)),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('email_address', models.EmailField(max_length=255)),
                ('mobile_number', models.CharField(help_text='Unique mobile number of the signatory', max_length=15, unique=True)),
                ('dsc_upload', models.FileField(blank=True, null=True, upload_to='signatory_documents/dsc/')),
                ('document_file_pan', models.FileField(upload_to='signatory_documents/pan_cards/')),
                ('document_file_aadhaar', models.FileField(upload_to='signatory_documents/aadhaar_cards/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='Pending', help_text='Current status of the signatory (Active/Pending).', max_length=10)),
                ('verified', models.BooleanField(default=False, help_text='Indicates whether the signatory has been verified.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatories', to='issuer_kyc.companyinformation')),
                ('user_id_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatory_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_signatory',
            },
        ),
        
          
       
     
        migrations.AddIndex(
            model_name='companyinformation',
            index=models.Index(fields=['user', 'del_flag'], name='company_kyc_user_id_341cde_idx'),
        ),
        migrations.AddIndex(
            model_name='companyinformation',
            index=models.Index(fields=['company_pan_number'], name='company_kyc_company_8eb3de_idx'),
        ),
        migrations.AddConstraint(
            model_name='companyinformation',
            constraint=models.UniqueConstraint(condition=models.Q(('del_flag', 0)), fields=('corporate_identification_number',), name='unique_cin_active_only'),
        ),
        migrations.AddConstraint(
            model_name='companyinformation',
            constraint=models.UniqueConstraint(condition=models.Q(('del_flag', 0)), fields=('company_pan_number',), name='unique_pan_active_only'),
        ),
        migrations.AddIndex(
            model_name='companydocument',
            index=models.Index(fields=['company', 'document_name'], name='company_doc_company_5a7e50_idx'),
        ),
        migrations.AddIndex(
            model_name='companydocument',
            index=models.Index(fields=['company', 'is_mandatory'], name='company_doc_company_42274f_idx'),
        ),
        migrations.AddIndex(
            model_name='companydocument',
            index=models.Index(fields=['uploaded_at'], name='company_doc_uploade_135a92_idx'),
        ),
        migrations.AddIndex(
            model_name='companydocument',
            index=models.Index(fields=['del_flag', 'company'], name='company_doc_del_fla_7196f4_idx'),
        ),
        migrations.AddIndex(
            model_name='bankdetails',
            index=models.Index(fields=['company', 'del_flag'], name='bank_detail_company_57f5fd_idx'),
        ),
        migrations.AddIndex(
            model_name='bankdetails',
            index=models.Index(fields=['ifsc_code'], name='bank_detail_ifsc_co_0c27af_idx'),
        ),
        migrations.AddIndex(
            model_name='companysignatory',
            index=models.Index(fields=['company'], name='company_sig_company_2876f8_idx'),
        ),
        migrations.AddIndex(
            model_name='companysignatory',
            index=models.Index(fields=['din'], name='company_sig_din_e768bb_idx'),
        ),
        migrations.AddIndex(
            model_name='companysignatory',
            index=models.Index(fields=['pan_number'], name='company_sig_pan_num_7e1fdb_idx'),
        ),
        migrations.AddIndex(
            model_name='companysignatory',
            index=models.Index(fields=['aadhaar_number'], name='company_sig_aadhaar_471da1_idx'),
        ),
        migrations.AddIndex(
            model_name='companysignatory',
            index=models.Index(fields=['status'], name='company_sig_status_a902c6_idx'),
        ),
        migrations.AddIndex(
            model_name='companysignatory',
            index=models.Index(fields=['mobile_number'], name='company_sig_mobile__ff2d3d_idx'),
        ),
        migrations.AddConstraint(
            model_name='companysignatory',
            constraint=models.UniqueConstraint(fields=('company', 'din'), name='unique_din_per_company'),
        ),
        migrations.AddConstraint(
            model_name='companysignatory',
            constraint=models.UniqueConstraint(fields=('mobile_number',), name='unique_mobile_number_signatory'),
        ),
       
       
       
    ]
