# Generated by Django 5.2.6 on 2025-11-03 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer_kyc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyonboardingapplication',
            name='company_information',
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_info', to='issuer_kyc.companyonboardingapplication'),
        ),
    ]
