# Generated by Django 5.2.6 on 2025-11-04 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuer_kyc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyaddress',
            name='application',
        ),
    ]
