# Generated by Django 5.2.6 on 2025-11-05 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer_kyc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DematAccount',
            fields=[
                ('del_flag', models.SmallIntegerField(default=0, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demat_account_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dp_name', models.CharField(max_length=50)),
                ('depository_participant', models.CharField(choices=[('NSDL', 'NSDL'), ('CDSL', 'CDSL')], max_length=10)),
                ('dp_id', models.CharField(max_length=20)),
                ('demat_account_number', models.CharField(max_length=50, unique=True)),
                ('client_id_bo_id', models.CharField(blank=True, max_length=20, null=True)),
                ('user_id_updated_by', models.BigIntegerField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demat_account', to='issuer_kyc.companyinformation')),
            ],
            options={
                'db_table': 'demat_accounts',
                'indexes': [models.Index(fields=['company', 'del_flag'], name='demat_accou_company_ce4549_idx'), models.Index(fields=['dp_id'], name='demat_accou_dp_id_b74c49_idx')],
            },
        ),
    ]
