# Generated by Django 5.2.6 on 2025-11-07 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer_kyc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companysignatory',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active')], default='PENDING', help_text='Current status of the signatory (Active/Pending).', max_length=10),
        ),
        migrations.AddField(
            model_name='companysignatory',
            name='verified',
            field=models.BooleanField(default=False, help_text='Indicates whether the signatory has been verified.'),
        ),
        migrations.AlterField(
            model_name='companysignatory',
            name='designation',
            field=models.CharField(choices=[('DIRECTOR', 'Director'), ('SIGNATORY', 'Signatory'), ('MANAGER', 'Manager')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='companysignatory',
            index=models.Index(fields=['status'], name='company_sig_status_a902c6_idx'),
        ),
    ]
