# Generated by Django 5.2.6 on 2025-11-11 11:44

import apps.kyc.issuer_kyc.utils.financial_documents.financial_document_path
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issuer_kyc", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialDocument",
            fields=[
                (
                    "del_flag",
                    models.SmallIntegerField(default=0, help_text="Soft delete flag"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("document_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("GSTR_3B", "GSTR-3B"),
                            ("GSTR_9", "GSTR-9"),
                            ("ITR", "Income Tax Return"),
                            ("FINANCIAL_STATEMENT", "Audited Financial Statement"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "document_tag",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PROVISIONAL", "Provisional"),
                            ("AUDITED", "Audited"),
                        ],
                        max_length=20,
                    ),
                ),
                ("financial_year", models.CharField(max_length=9)),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("YEARLY", "Yearly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("period_start_date", models.DateField()),
                ("period_end_date", models.DateField()),
                ("period_code", models.CharField(blank=True, max_length=20, null=True)),
                ("version", models.SmallIntegerField(default=1)),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_path",
                    models.FileField(
                        blank=True,
                        max_length=500,
                        null=True,
                        upload_to=apps.kyc.issuer_kyc.utils.financial_documents.financial_document_path.financial_document_upload_path,
                    ),
                ),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                (
                    "mime_type",
                    models.CharField(default="application/pdf", max_length=100),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "verification_source",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Verification"),
                            ("GST_PORTAL", "GST Portal API"),
                            ("INCOME_TAX_API", "Income Tax API"),
                            ("THIRD_PARTY_API", "Third Party Verification"),
                            ("MANUAL", "Manual Verification"),
                        ],
                        default="PENDING",
                        max_length=100,
                    ),
                ),
                (
                    "verification_reference_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "auditor_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("audit_report_date", models.DateField(blank=True, null=True)),
                (
                    "audit_firm_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="financial_documents",
                        to="issuer_kyc.companyinformation",
                    ),
                ),
                (
                    "user_id_updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "financial_documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "document_type"],
                        name="financial_d_company_240d66_idx",
                    ),
                    models.Index(
                        fields=["financial_year", "document_tag"],
                        name="financial_d_financi_afade7_idx",
                    ),
                    models.Index(
                        fields=["period_start_date", "period_end_date"],
                        name="financial_d_period__b06a1b_idx",
                    ),
                    models.Index(
                        fields=["is_verified", "verification_source"],
                        name="financial_d_is_veri_8a01fd_idx",
                    ),
                ],
                "unique_together": {
                    (
                        "company",
                        "document_type",
                        "period_start_date",
                        "period_end_date",
                        "document_tag",
                        "version",
                    )
                },
            },
        ),
    ]
