# Generated by Django 5.2.6 on 2025-11-04 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer_kyc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='companyonboardingapplication',
            name='company_onb_current_262d67_idx',
        ),
        migrations.RenameField(
            model_name='companyonboardingapplication',
            old_name='current_step',
            new_name='last_accessed_step',
        ),
        migrations.AddIndex(
            model_name='companyonboardingapplication',
            index=models.Index(fields=['last_accessed_step'], name='company_onb_last_ac_4eecd1_idx'),
        ),
    ]
