# Generated by Django 5.2.6 on 2025-11-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer_kyc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaddress',
            name='address_proof_file',
            field=models.FileField(blank=True, help_text='Path to the uploaded address proof document', null=True, upload_to='uploads/company_address/'),
        ),
    ]
