# Generated by Django 5.2.6 on 2025-11-07 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer_kyc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('del_flag', models.SmallIntegerField(default=0, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_detail_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cancelled_cheque', models.FileField(blank=True, null=True, upload_to='onboarding/bank/cancelled_cheques/')),
                ('bank_statement', models.FileField(blank=True, null=True, upload_to='onboarding/bank/statements/')),
                ('passbook', models.FileField(blank=True, null=True, upload_to='onboarding/bank/passbooks/')),
                ('bank_name', models.CharField(max_length=100)),
                ('branch_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=30)),
                ('account_type', models.CharField(choices=[('SAVINGS', 'Savings'), ('CURRENT', 'Current')], max_length=20)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(null=True)),
                ('verified_data_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='issuer_kyc.companyinformation')),
                ('user_id_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bank_details',
                'indexes': [models.Index(fields=['company', 'del_flag'], name='bank_detail_company_57f5fd_idx'), models.Index(fields=['ifsc_code'], name='bank_detail_ifsc_co_0c27af_idx')],
            },
        ),
    ]
