# Generated by Django 5.2.6 on 2025-11-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuer_kyc', '0002_financialdocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinformation',
            options={},
        ),
    ]
