# Generated by Django 5.2.6 on 2025-11-08 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("issuer_kyc", "0002_companyaddress_address_proof_file"),
        ("issuer_kyc", "0002_demataccount"),
    ]

    operations = []
