# Generated by Django 5.2.6 on 2025-11-05 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuer_kyc', '0002_remove_companyonboardingapplication_company_onb_current_262d67_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='companyonboardingapplication',
            name='company_onb_last_ac_4eecd1_idx',
        ),
    ]
