# Generated by Django 5.2.6 on 2025-11-17 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issuer_kyc", "0003_alter_companyinformation_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinformation",
            name="city_of_incorporation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="companyinformation",
            name="country_of_incorporation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="companyinformation",
            name="sector",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AGRICULTURE", "Agriculture"),
                    ("MANUFACTURING", "Manufacturing"),
                    ("IT_SOFTWARE", "IT & Software"),
                    ("FINANCIAL", "Financial Services"),
                    ("HEALTHCARE", "Healthcare"),
                    ("RETAIL", "Retail & E-commerce"),
                    ("REAL_ESTATE", "Real Estate"),
                    ("LOGISTICS", "Logistics & Transportation"),
                    ("ENTERTAINMENT", "Media & Entertainment"),
                    ("EDUCATION", "Education"),
                    ("OTHERS", "Others"),
                ],
                max_length=50,
                null=True,
            ),
        ),

        migrations.AlterField(
            model_name="companyinformation",
            name="company_pan_number",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="companyinformation",
            name="corporate_identification_number",
            field=models.CharField(max_length=21),
        ),
        migrations.AlterField(
            model_name="companyinformation",
            name="state_of_incorporation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),

        # ❌ Removed the BAD index on ["user", "del_flag"]

        migrations.AddIndex(
            model_name="companyinformation",
            index=models.Index(
                fields=["company_pan_number"], 
                name="company_kyc_company_8eb3de_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="companyinformation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("del_flag", 0)),
                fields=("corporate_identification_number",),
                name="unique_cin_active_only",
            ),
        ),
        migrations.AddConstraint(
            model_name="companyinformation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("del_flag", 0)),
                fields=("company_pan_number",),
                name="unique_pan_active_only",
            ),
        ),
        
    ]
