# Generated by Django 5.2.6 on 2025-11-06 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuer_kyc', '0004_bankdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetails',
            name='status',
        ),
        migrations.RemoveField(
            model_name='bankdetails',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='bankdetails',
            name='verification_errors',
        ),
    ]
