# Generated by Django 5.2.6 on 2025-11-17 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issuer_kyc", "0004_companyinformation_city_of_incorporation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyinformation",
            name="place_of_incorporation",
        ),
       
    
    ]
