# Generated by Django 5.2.6 on 2025-11-17 10:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer_kyc', '0005_remove_companyinformation_place_of_incorporation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUploadedFile',
            fields=[
                ('temp_file_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.TextField()),
                ('original_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
       
        migrations.AlterField(
            model_name='companysignatory',
            name='designation',
            field=models.CharField(choices=[('DIRECTOR', 'Director'), ('SIGNATORY', 'Signatory'), ('MANAGER', 'Manager')], max_length=50),
        ),
        migrations.AlterField(
            model_name='companysignatory',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='PENDING', help_text='Current status of the signatory (Active/Pending).', max_length=10),
        ),
       
        migrations.AddField(
            model_name='tempuploadedfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
