# Generated by Django 5.2.6 on 2025-11-07 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuer_kyc', '0002_companyaddress_address_proof_file'),
        ('issuer_kyc', '0002_demataccount'),
        ('issuer_kyc', '0005_remove_bankdetails_status_and_more'),
    ]

    operations = [
    ]
