# Generated by Django 5.2.6 on 2025-11-19 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "issuer_kyc",
            "0005_remove_companyinformation_place_of_incorporation_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
       
      
        migrations.AddField(
            model_name="companysignatory",
            name="mobile_number",
            field=models.CharField(
                blank=True,
                help_text="Unique mobile number of the signatory",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="companysignatory",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Active", "Active"),
                    ("Inactive", "Inactive"),
                ],
                default="Pending",
                help_text="Current status of the signatory (Active/Pending).",
                max_length=10,
            ),
        ),
        
        migrations.AddIndex(
            model_name="companysignatory",
            index=models.Index(
                fields=["mobile_number"], name="company_sig_mobile__ff2d3d_idx"
            ),
        ),
    ]