# Generated by Django 5.2.6 on 2025-11-19 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issuer_kyc", "0006_companyinformation_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        
        migrations.AlterField(
            model_name="companysignatory",
            name="designation",
            field=models.CharField(
                choices=[
                    ("DIRECTOR", "Director"),
                    ("SIGNATORY", "Signatory"),
                    ("MANAGER", "Manager"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="companysignatory",
            name="mobile_number",
            field=models.CharField(
                help_text="Unique mobile number of the signatory",
                max_length=15,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="companysignatory",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                ],
                default="Pending",
                help_text="Current status of the signatory (Active/Pending).",
                max_length=10,
            ),
        ),
       
        migrations.AddConstraint(
            model_name="companysignatory",
            constraint=models.UniqueConstraint(
                fields=("mobile_number",), name="unique_mobile_number_signatory"
            ),
        ),
        
    ]

    
