# Generated by Django 5.2.6 on 2025-11-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer_kyc', '0006_merge_20251107_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='verified_data_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
