# Generated by Django 5.2.6 on 2025-11-19 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer_kyc', '0006_tempuploadedfile_companyinformation_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='user_id_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='sector',
            field=models.CharField(blank=True, choices=[('BANKING', 'banking'), ('INFRASTRUCTURE', 'Infrastructure'), ('POWER', 'Power '), ('REAL ESTATE', 'Real Estate'), ('MANUFACTURING', 'Manufacturing'), ('IT', 'IT & Software'), ('PUBLIC SECTOR UNDERTAKING', 'Public Sector Undertaking'), ('OTHERS', 'Others')], max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='companyinformation',
            index=models.Index(fields=['user', 'del_flag'], name='company_kyc_user_id_341cde_idx'),
        ),
    ]
