# Generated by Django 5.2.6 on 2025-11-19 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("issuer_kyc", "0006_tempuploadedfile_companyinformation_user_and_more"),
        ("issuer_kyc", "0007_companyinformation_user_and_more"),
    ]

    operations = []
