# Generated by Django 5.2.6 on 2025-11-19 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issuer_kyc", "0008_merge_20251119_1642"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinformation",
            name="human_intervention",
            field=models.BooleanField(
                default=False, help_text="Flag to indicate manual review requirement."
            ),
        ),
        
        
        migrations.AddField(
            model_name="companyinformation",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending - Human intervention required"),
                    ("SUCCESS", "Successfully Verified"),
                    ("FAILED", "Failed Verification"),
                ],
                default="PENDING",
                help_text="Current verification state of the company KYC.",
                max_length=20,
            ),
        ),
        
        migrations.AlterField(
            model_name="companysignatory",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                ],
                default="Pending",
                help_text="Current status of the signatory (Active/Pending).",
                max_length=10,
            ),
        ),
        
    ]
