# Generated by Django 5.2.6 on 2025-11-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='isinbasicinfo',
            name='prepetual',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='isinrating',
            name='credit_rating',
            field=models.CharField(choices=[('AAA', 'AAA'), ('AA+', 'AA+'), ('AA', 'AA'), ('AA-', 'AA-'), ('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('BBB+', 'BBB+'), ('BBB', 'BBB'), ('BBB-', 'BBB-'), ('BB+', 'BB+'), ('BB', 'BB'), ('BB-', 'BB-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C', 'C'), ('D', 'Default / D'), ('UNRATED', 'Unrated / No Rating')], max_length=10),
        ),
    ]
