# Generated by Django 5.2.6 on 2025-10-14 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactmessage',
            table='frontend_contactmessage',
        ),
    ]
