# Generated by Django 5.2.6 on 2025-11-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bonds", "0002_isinbasicinfo_prepetual_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="isinrating",
            name="rating_agency",
            field=models.CharField(
                choices=[
                    ("CRISIL", "CRISIL"),
                    ("ICRA", "ICRA"),
                    ("CARE", "CARE Ratings"),
                    ("IND-RA", "India Ratings & Research"),
                    ("BWR", "Brickwork Ratings"),
                    ("ACUITE", "Acuité Ratings"),
                    ("INFOMERICS", "Infomerics"),
                ],
                max_length=100,
            ),
        ),
    ]
