# Generated by Django 5.2.6 on 2025-09-27 08:22

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OTPRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        help_text="Phone number with country code",
                        max_length=128,
                        region=None,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("registration", "Registration"),
                            ("login", "Login"),
                            ("password_reset", "Password Reset"),
                            ("phone_verification", "Phone Verification"),
                        ],
                        default="registration",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("verified", "Verified"),
                            ("expired", "Expired"),
                            ("failed", "Failed"),
                        ],
                        default="sent",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "external_reference",
                    models.CharField(
                        blank=True,
                        help_text="External service reference (e.g., Twilio SID)",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "auth_otp_requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["phone_number", "purpose"], name="otp_phone_purpose_idx"
                    ),
                    models.Index(
                        fields=["phone_number", "status"], name="otp_phone_status_idx"
                    ),
                    models.Index(fields=["created_at"], name="otp_created_idx"),
                    models.Index(fields=["expires_at"], name="otp_expires_idx"),
                    models.Index(
                        fields=["status", "created_at"], name="otp_status_created_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("attempt_count__gte", 0)),
                        name="otp_attempt_count_positive",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OTPAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_successful", models.BooleanField(default=False)),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "otp_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="authentication.otprequest",
                    ),
                ),
            ],
            options={
                "db_table": "auth_otp_attempts",
                "ordering": ["-attempted_at"],
                "indexes": [
                    models.Index(
                        fields=["otp_request", "attempted_at"],
                        name="otp_attempt_request_time_idx",
                    ),
                    models.Index(fields=["attempted_at"], name="otp_attempt_time_idx"),
                    models.Index(
                        fields=["is_successful"], name="otp_attempt_success_idx"
                    ),
                ],
            },
        ),
    ]
