# Generated by Django 5.2.6 on 2025-11-12 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20251111_1910'),
        ('authentication', '0002_user_unique_email_when_present'),
    ]

    operations = [
    ]
