# Generated by Django 5.2.6 on 2025-11-21 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issuer_kyc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowingDetail',
            fields=[
                ('borrowing_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lender_name', models.CharField(max_length=255)),
                ('lender_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('borrowing_type', models.CharField(choices=[('TERM_LOAN', 'Term Loan'), ('WC', 'Working Capital'), ('ECB', 'External Commercial Borrowing')], max_length=50)),
                ('repayment_terms', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], max_length=50)),
                ('monthly_principal_payment', models.DecimalField(decimal_places=2, max_digits=18)),
                ('interest_payment_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monthly_interest_payment', models.DecimalField(decimal_places=2, max_digits=18)),
                ('is_del', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowings_old', to='issuer_kyc.companyinformation')),
                ('user_id_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'roi_borrowing_detail',
                'indexes': [models.Index(fields=['company', 'is_del'], name='roi_borrowi_company_09a163_idx')],
            },
        ),
        migrations.CreateModel(
            name='CapitalDetail',
            fields=[
                ('capital_detail_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('share_capital', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reserves_surplus', models.DecimalField(decimal_places=2, max_digits=18)),
                ('net_worth', models.DecimalField(decimal_places=2, max_digits=18)),
                ('is_del', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_details_old', to='issuer_kyc.companyinformation')),
                ('user_id_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'roi_capital_detail',
                'indexes': [models.Index(fields=['company', 'is_del'], name='roi_capital_company_baa974_idx')],
            },
        ),
        migrations.CreateModel(
            name='CreditRating',
            fields=[
                ('credit_rating_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('agency', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=10)),
                ('valid_till', models.DateField()),
                ('additional_rating', models.CharField(blank=True, max_length=255, null=True)),
                ('upload_letter', models.FileField(blank=True, null=True, upload_to='uploads/credit_ratings/')),
                ('is_del', models.SmallIntegerField(default=0)),
                ('reting_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_ratings_old', to='issuer_kyc.companyinformation')),
                ('user_id_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'roi_credit_rating',
                'indexes': [models.Index(fields=['company', 'is_del'], name='roi_credit__company_b681c0_idx')],
            },
        ),
        migrations.CreateModel(
            name='FundPosition',
            fields=[
                ('fund_position_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cash_balance_as_on_date', models.DateField()),
                ('bank_balance_as_on_date', models.DateField()),
                ('cash_balance_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('bank_balance_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_del', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roi_fund_positions', to='issuer_kyc.companyinformation')),
                ('user_id_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'roi_fund_position',
                'indexes': [models.Index(fields=['company', 'is_del'], name='roi_fund_po_company_2f454d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProfitabilityRatio',
            fields=[
                ('ratio_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('net_worth', models.DecimalField(decimal_places=2, max_digits=18)),
                ('ebitda', models.DecimalField(decimal_places=2, max_digits=18)),
                ('debt_equity_ratio', models.DecimalField(decimal_places=4, max_digits=10)),
                ('current_ratio', models.DecimalField(decimal_places=4, max_digits=10)),
                ('quick_ratio', models.DecimalField(decimal_places=4, max_digits=10)),
                ('return_on_equity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('return_on_assets', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dscr', models.DecimalField(decimal_places=4, max_digits=10)),
                ('is_del', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profitability_ratios_old', to='issuer_kyc.companyinformation')),
                ('user_id_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'roi_profitability_ratio',
                'indexes': [models.Index(fields=['company', 'is_del'], name='roi_profita_company_2b0675_idx')],
            },
        ),
    ]
