# Generated by Django 5.2.6 on 2025-11-18 10:29

import apps.bond_estimate.models.CollateralAssetVerificationModel
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issuer_kyc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowingDetails',
            fields=[
                ('borrowing_id', models.UUIDField(db_column='borrowing_id', default=uuid.uuid4, editable=False, help_text='Unique identifier for borrowing record', primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(db_column='company_id', db_index=True, help_text='Foreign key reference to company_kyc table')),
                ('lender_name', models.CharField(db_column='lender_name', help_text='Name of the lending institution', max_length=255)),
                ('lender_amount', models.DecimalField(db_column='lender_amount', decimal_places=2, help_text='Amount borrowed in currency', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('borrowing_type', models.CharField(choices=[('Secured', 'Secured'), ('Unsecured', 'Unsecured'), ('Short Term', 'Short Term'), ('Long Term', 'Long Term'), ('Internal', 'Internal'), ('External', 'External')], db_column='borrowing_type', help_text='Type of borrowing (Term Loan/WC/ECB)', max_length=50)),
                ('repayment_terms', models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Half Yearly', 'Half Yearly'), ('Annually', 'Annually')], db_column='repayment_terms', help_text='Frequency of repayment', max_length=50)),
                ('monthly_principal_payment', models.DecimalField(db_column='monthly_principal_payment', decimal_places=2, help_text='Monthly principal payment amount', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('interest_payment_percentage', models.DecimalField(blank=True, db_column='interest_payment_percentage', decimal_places=2, help_text='Interest rate percentage (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('monthly_interest_payment', models.DecimalField(db_column='monthly_interest_payment', decimal_places=2, help_text='Monthly interest payment amount', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_del', models.SmallIntegerField(db_column='is_del', default=0, help_text='Soft delete flag (0=active, 1=deleted)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', help_text='Last modification timestamp')),
                ('user_id_updated_by', models.UUIDField(blank=True, db_column='user_id_updated_by', help_text='User ID who last updated the record', null=True)),
            ],
            options={
                'verbose_name': 'Borrowing Detail',
                'verbose_name_plural': 'Borrowing Details',
                'db_table': 'borrowing_details',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company_id', 'is_del'], name='idx_company_active'), models.Index(fields=['borrowing_type'], name='idx_borrowing_type'), models.Index(fields=['created_at'], name='idx_created_at'), models.Index(fields=['is_del', 'company_id', '-created_at'], name='idx_active_company_date')],
            },
        ),
        migrations.CreateModel(
            name='BondEstimationApplication',
            fields=[
                ('application_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('READY_FOR_CALCULATION', 'Ready For Calculation'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=30)),
                ('last_accessed_step', models.IntegerField(default=1, help_text='Last step user visited (analytics only)')),
                ('step_progress', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Linked company for which the rating is issued.', on_delete=django.db.models.deletion.CASCADE, related_name='bond_estimations', to='issuer_kyc.companyinformation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bond_estimations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bond_estimation_applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='bond_estima_company_510c94_idx'), models.Index(fields=['user', 'created_at'], name='bond_estima_user_id_7d64c3_idx')],
            },
        ),
        migrations.CreateModel(
            name='CapitalDetails',
            fields=[
                ('del_flag', models.SmallIntegerField(default=0, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capital_detail_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('share_capital', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reserves_surplus', models.DecimalField(decimal_places=2, max_digits=18)),
                ('net_worth', models.DecimalField(decimal_places=2, max_digits=18)),
                ('company', models.ForeignKey(help_text='Linked company for which the rating is issued.', on_delete=django.db.models.deletion.CASCADE, related_name='captial_ratings', to='issuer_kyc.companyinformation')),
                ('user_id_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'capital_details',
                'indexes': [models.Index(fields=['company'], name='capital_det_company_83cf62_idx')],
            },
        ),
        migrations.CreateModel(
            name='CollateralAssetVerification',
            fields=[
                ('del_flag', models.SmallIntegerField(default=0, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collateral_type', models.CharField(choices=[('Land', 'Land'), ('Equipment', 'Equipment'), ('Receivables', 'Receivables'), ('Shares', 'Shares'), ('Project Assets', 'Project Assets')], max_length=50)),
                ('charge_type', models.CharField(choices=[('First Charge', 'First Charge'), ('Second Charge', 'Second Charge'), ('Exclusive Charge', 'Exclusive Charge'), ('Pari Passu Charge', 'Pari Passu Charge'), ('Subservient Charge', 'Subservient Charge')], max_length=50)),
                ('asset_description', models.TextField()),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('valuation_date', models.DateField()),
                ('security_document_file', models.FileField(blank=True, max_length=500, null=True, upload_to=apps.bond_estimate.models.CollateralAssetVerificationModel.security_document_upload_path)),
                ('security_document_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('trust_name', models.CharField(max_length=255)),
                ('ownership_type', models.CharField(choices=[('Owned', 'Owned'), ('Leased', 'Leased'), ('Pledged', 'Pledged')], max_length=50)),
                ('asset_cover_certificate', models.FileField(blank=True, max_length=500, null=True, upload_to=apps.bond_estimate.models.CollateralAssetVerificationModel.asset_cover_certificate_upload_path)),
                ('valuation_report', models.FileField(blank=True, max_length=500, null=True, upload_to=apps.bond_estimate.models.CollateralAssetVerificationModel.valuation_report_upload_path)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collateral_assets', to='issuer_kyc.companyinformation')),
                ('user_id_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'collateral_asset_verification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'del_flag'], name='collateral__company_08769d_idx'), models.Index(fields=['collateral_type'], name='collateral__collate_ffe471_idx'), models.Index(fields=['charge_type'], name='collateral__charge__8b907f_idx'), models.Index(fields=['ownership_type'], name='collateral__ownersh_097a4f_idx'), models.Index(fields=['created_at'], name='collateral__created_4abfe6_idx')],
            },
        ),
        migrations.CreateModel(
            name='CreditRatingDetails',
            fields=[
                ('del_flag', models.SmallIntegerField(default=0, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_rating_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('agency', models.CharField(choices=[('CRISIL', 'CRISIL'), ('ICRA', 'ICRA'), ('CARE', 'CARE Ratings'), ('IND-RA', 'India Ratings & Research'), ('BWR', 'Brickwork Ratings'), ('ACUITE', 'Acuité Ratings')], help_text='Credit rating agency (e.g., CRISIL, ICRA, CARE, etc.).', max_length=50)),
                ('rating', models.CharField(choices=[('AAA', 'AAA'), ('AA+', 'AA+'), ('AA', 'AA'), ('AA-', 'AA-'), ('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('BBB+', 'BBB+'), ('UNRATED', 'UNRATED')], help_text='Rating value (e.g., AA (Stable), BBB+, etc.).', max_length=10)),
                ('valid_till', models.DateField(help_text='Expiration date of this credit rating.')),
                ('additional_rating', models.CharField(blank=True, help_text='Optional remarks or additional rating comments.', max_length=255, null=True)),
                ('upload_letter', models.FileField(blank=True, help_text='Encrypted uploaded PDF of the official credit rating letter.', null=True, upload_to='credit_ratings/letters/')),
                ('reting_status', models.BooleanField(default=False, help_text='True if the rating is active/valid; False if expired or invalid.')),
                ('is_del', models.SmallIntegerField(default=0, help_text='Logical delete flag — 0 = active, 1 = deleted.')),
                ('company', models.ForeignKey(help_text='Linked company for which the rating is issued.', on_delete=django.db.models.deletion.CASCADE, related_name='credit_ratings', to='issuer_kyc.companyinformation')),
                ('user_id_updated_by', models.ForeignKey(blank=True, help_text='User/admin who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_rating_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credit_rating_details',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company'], name='credit_rati_company_6be55e_idx'), models.Index(fields=['agency'], name='credit_rati_agency_bae902_idx'), models.Index(fields=['rating'], name='credit_rati_rating_05fcb4_idx'), models.Index(fields=['valid_till'], name='credit_rati_valid_t_6e27e3_idx'), models.Index(fields=['reting_status'], name='credit_rati_reting__b43aac_idx')],
            },
        ),
        migrations.CreateModel(
            name='FundPosition',
            fields=[
                ('del_flag', models.SmallIntegerField(default=0, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund_position_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Primary key (UUID)', primary_key=True, serialize=False)),
                ('cash_balance_date', models.DateField(db_index=True, help_text='Date of cash balance')),
                ('bank_balance_date', models.DateField(db_index=True, help_text='Date of bank balance')),
                ('cash_balance_amount', models.DecimalField(decimal_places=2, help_text='Cash balance amount', max_digits=15)),
                ('bank_balance_amount', models.DecimalField(decimal_places=2, help_text='Bank balance amount', max_digits=15)),
                ('remarks', models.TextField(blank=True, help_text='Optional remarks', null=True)),
                ('company', models.ForeignKey(db_column='company_id', help_text='Reference to company', on_delete=django.db.models.deletion.CASCADE, related_name='fund_positions', to='issuer_kyc.companyinformation')),
                ('user_id_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fund_position',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'del_flag'], name='idx_fund_pos_comp_del'), models.Index(fields=['company', 'cash_balance_date'], name='idx_fund_pos_comp_cash_dt'), models.Index(fields=['company', 'bank_balance_date'], name='idx_fund_pos_comp_bank_dt'), models.Index(fields=['user_id_updated_by', 'created_at'], name='idx_fund_pos_user_created'), models.Index(fields=['company', 'del_flag', 'created_at'], name='idx_fund_pos_list')],
                'constraints': [models.CheckConstraint(condition=models.Q(('cash_balance_amount__gte', 0)), name='check_cash_balance_positive'), models.CheckConstraint(condition=models.Q(('bank_balance_amount__gte', 0)), name='check_bank_balance_positive'), models.CheckConstraint(condition=models.Q(('del_flag__in', [0, 1])), name='check_del_flag_valid')],
            },
        ),
        migrations.CreateModel(
            name='PreliminaryBondRequirements',
            fields=[
                ('del_flag', models.SmallIntegerField(default=0, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('security_type', models.CharField(choices=[('Secured', 'Secured'), ('Unsecured', 'Unsecured')], max_length=20)),
                ('tenure', models.DecimalField(decimal_places=2, help_text='Tenure in years', max_digits=5)),
                ('preferred_roi', models.DecimalField(decimal_places=2, help_text='Preferred ROI %', max_digits=5)),
                ('coupon_rate', models.DecimalField(decimal_places=2, help_text='Coupon Rate %', max_digits=5)),
                ('preferred_investor_categories', models.JSONField()),
                ('preferred_interest_payment_cycle', models.JSONField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preliminary_bond_requirements', to='issuer_kyc.companyinformation')),
                ('user_id_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'preliminary_bond_requirements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'del_flag'], name='preliminary_company_b58759_idx'), models.Index(fields=['security_type'], name='preliminary_securit_d00390_idx'), models.Index(fields=['issue_amount'], name='preliminary_issue_a_dd6396_idx'), models.Index(fields=['coupon_rate'], name='preliminary_coupon__d522e6_idx'), models.Index(fields=['created_at'], name='preliminary_created_0bd5e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProfitabilityRatios',
            fields=[
                ('del_flag', models.SmallIntegerField(default=0, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ratio_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('net_profit', models.DecimalField(blank=True, decimal_places=2, help_text='Net profit amount', max_digits=18, null=True)),
                ('net_worth', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('ebitda', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('debt_equity_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('current_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('quick_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('return_on_equity', models.DecimalField(blank=True, decimal_places=2, help_text='ROE percentage', max_digits=5, null=True)),
                ('return_on_assets', models.DecimalField(blank=True, decimal_places=2, help_text='ROA percentage', max_digits=5, null=True)),
                ('dscr', models.DecimalField(blank=True, decimal_places=4, help_text='Debt-Service Coverage Ratio', max_digits=10, null=True)),
                ('company', models.ForeignKey(blank=True, help_text='Company for which the profitability and ratios are recorded.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profitability_ratios', to='issuer_kyc.companyinformation')),
                ('user_id_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profitability_ratios',
                'indexes': [models.Index(fields=['company'], name='profitabili_company_ca2879_idx')],
            },
        ),
    ]
