# Generated by Django 5.2.6 on 2025-11-11 11:44

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("issuer_kyc", "0002_financialdocument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BorrowingDetails",
            fields=[
                (
                    "borrowing_id",
                    models.UUIDField(
                        db_column="borrowing_id",
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for borrowing record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company_id",
                    models.UUIDField(
                        db_column="company_id",
                        db_index=True,
                        help_text="Foreign key reference to company_kyc table",
                    ),
                ),
                (
                    "lender_name",
                    models.CharField(
                        db_column="lender_name",
                        help_text="Name of the lending institution",
                        max_length=255,
                    ),
                ),
                (
                    "lender_amount",
                    models.DecimalField(
                        db_column="lender_amount",
                        decimal_places=2,
                        help_text="Amount borrowed in currency",
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "borrowing_type",
                    models.CharField(
                        choices=[
                            ("Secured", "Secured"),
                            ("Unsecured", "Unsecured"),
                            ("Short Term", "Short Term"),
                            ("Long Term", "Long Term"),
                            ("Internal", "Internal"),
                            ("External", "External"),
                        ],
                        db_column="borrowing_type",
                        help_text="Type of borrowing (Term Loan/WC/ECB)",
                        max_length=50,
                    ),
                ),
                (
                    "repayment_terms",
                    models.CharField(
                        choices=[
                            ("Monthly", "Monthly"),
                            ("Quarterly", "Quarterly"),
                            ("Half Yearly", "Half Yearly"),
                            ("Annually", "Annually"),
                        ],
                        db_column="repayment_terms",
                        help_text="Frequency of repayment",
                        max_length=50,
                    ),
                ),
                (
                    "monthly_principal_payment",
                    models.DecimalField(
                        db_column="monthly_principal_payment",
                        decimal_places=2,
                        help_text="Monthly principal payment amount",
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "interest_payment_percentage",
                    models.DecimalField(
                        blank=True,
                        db_column="interest_payment_percentage",
                        decimal_places=2,
                        help_text="Interest rate percentage (0-100)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "monthly_interest_payment",
                    models.DecimalField(
                        db_column="monthly_interest_payment",
                        decimal_places=2,
                        help_text="Monthly interest payment amount",
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "is_del",
                    models.SmallIntegerField(
                        db_column="is_del",
                        default=0,
                        help_text="Soft delete flag (0=active, 1=deleted)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="created_at",
                        help_text="Record creation timestamp",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_column="updated_at",
                        help_text="Last modification timestamp",
                    ),
                ),
                (
                    "user_id_updated_by",
                    models.UUIDField(
                        blank=True,
                        db_column="user_id_updated_by",
                        help_text="User ID who last updated the record",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Borrowing Detail",
                "verbose_name_plural": "Borrowing Details",
                "db_table": "borrowing_details",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company_id", "is_del"], name="idx_company_active"
                    ),
                    models.Index(fields=["borrowing_type"], name="idx_borrowing_type"),
                    models.Index(fields=["created_at"], name="idx_created_at"),
                    models.Index(
                        fields=["is_del", "company_id", "-created_at"],
                        name="idx_active_company_date",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BondEstimationApplication",
            fields=[
                (
                    "application_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("IN_PROGRESS", "In Progress"),
                            ("READY_FOR_CALCULATION", "Ready For Calculation"),
                            ("COMPLETED", "Completed"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                (
                    "last_accessed_step",
                    models.IntegerField(
                        default=1, help_text="Last step user visited (analytics only)"
                    ),
                ),
                ("step_progress", models.JSONField(blank=True, default=dict)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bond_estimations",
                        to="issuer_kyc.companyinformation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bond_estimations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bond_estimation_applications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "status"],
                        name="bond_estima_company_510c94_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="bond_estima_user_id_7d64c3_idx",
                    ),
                ],
            },
        ),
    ]
