# Generated by Django 5.2.6 on 2025-11-21 10:33

import apps.bond_estimate.models.CollateralAssetVerificationModel
import apps.bond_estimate.utils.financial_documents.financial_document_path
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("issuer_kyc", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BondEstimationApplication",
            fields=[
                (
                    "application_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("IN_PROGRESS", "In Progress"),
                            ("READY_FOR_CALCULATION", "Ready For Calculation"),
                            ("COMPLETED", "Completed"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                (
                    "last_accessed_step",
                    models.IntegerField(
                        default=1, help_text="Last step user visited (analytics only)"
                    ),
                ),
                ("step_progress", models.JSONField(blank=True, default=dict)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Linked company for which the rating is issued.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bond_estimations",
                        to="issuer_kyc.companyinformation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bond_estimations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bond_estimation_applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BorrowingDetails",
            fields=[
                (
                    "borrowing_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lender_name", models.CharField(max_length=255)),
                (
                    "lender_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "borrowing_type",
                    models.CharField(
                        choices=[
                            ("SECURED", "Secured"),
                            ("UNSECURED", "Unsecured"),
                            ("SHORT-TERM", "Short Term"),
                            ("LONG-TERM", "Long Term"),
                            ("INTERNAL", "Internal"),
                            ("EXTERNAL", "External"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "repayment_terms",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("HALF YEARLY", "Half Yearly"),
                            ("ANNUALLY", "Annually"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "monthly_principal_payment",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "interest_payment_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "monthly_interest_payment",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_del", models.SmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id_updated_by", models.UUIDField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        db_column="application_id",
                        help_text="Bond Estimation Application reference",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borrowing_details",
                        to="bond_estimate.bondestimationapplication",
                    ),
                ),
            ],
            options={
                "db_table": "borrowing_details",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CapitalDetails",
            fields=[
                (
                    "del_flag",
                    models.SmallIntegerField(default=0, help_text="Soft delete flag"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "capital_detail_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "share_capital",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "reserves_surplus",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "net_worth",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "application",
                    models.OneToOneField(
                        db_column="application_id",
                        help_text="Bond estimation application this capital data belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capital_details",
                        to="bond_estimate.bondestimationapplication",
                    ),
                ),
                (
                    "user_id_updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "capital_details",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CollateralAssetVerification",
            fields=[
                (
                    "del_flag",
                    models.SmallIntegerField(default=0, help_text="Soft delete flag"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collateral_asset_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "collateral_type",
                    models.CharField(
                        choices=[
                            ("LAND", "Land"),
                            ("EQUIPMENT", "Equipment"),
                            ("RECEIVABLES", "Receivables"),
                            ("SHARES", "Shares"),
                            ("PROJECT ASSETS", "Project Assets"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "charge_type",
                    models.CharField(
                        choices=[
                            ("FIRST CHARGE", "First Charge"),
                            ("SECOND CHARGE", "Second Charge"),
                            ("EXCLUSIVE CHARGE", "Exclusive Charge"),
                            ("PARI PASSU CHARGE", "Pari Passu Charge"),
                            ("SUBSERVIENT CHARGE", "Subservient Charge"),
                        ],
                        max_length=50,
                    ),
                ),
                ("asset_description", models.TextField()),
                (
                    "estimated_value",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("valuation_date", models.DateField()),
                (
                    "security_document_file",
                    models.FileField(
                        blank=True,
                        max_length=500,
                        null=True,
                        upload_to=apps.bond_estimate.models.CollateralAssetVerificationModel.security_document_upload_path,
                    ),
                ),
                (
                    "security_document_ref",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("trust_name", models.CharField(max_length=255)),
                (
                    "ownership_type",
                    models.CharField(
                        choices=[
                            ("OWNED", "Owned"),
                            ("LEASED", "Leased"),
                            ("PLEDGED", "Pledged"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "asset_cover_certificate",
                    models.FileField(
                        blank=True,
                        max_length=500,
                        null=True,
                        upload_to=apps.bond_estimate.models.CollateralAssetVerificationModel.asset_cover_certificate_upload_path,
                    ),
                ),
                (
                    "valuation_report",
                    models.FileField(
                        blank=True,
                        max_length=500,
                        null=True,
                        upload_to=apps.bond_estimate.models.CollateralAssetVerificationModel.valuation_report_upload_path,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "application",
                    models.OneToOneField(
                        db_column="application_id",
                        help_text="Bond estimation application this collateral belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collateral_asset_verification",
                        to="bond_estimate.bondestimationapplication",
                    ),
                ),
                (
                    "user_id_updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "collateral_asset_verification",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CreditRatingDetails",
            fields=[
                (
                    "del_flag",
                    models.SmallIntegerField(default=0, help_text="Soft delete flag"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "credit_rating_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "agency",
                    models.CharField(
                        choices=[
                            ("CRISIL", "CRISIL"),
                            ("ICRA", "ICRA"),
                            ("CARE", "CARE Ratings"),
                            ("IND-RA", "India Ratings & Research"),
                            ("BWR", "Brickwork Ratings"),
                            ("ACUITE", "Acuité Ratings"),
                        ],
                        help_text="Credit rating agency (e.g., CRISIL, ICRA, CARE, etc.).",
                        max_length=50,
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("AAA", "AAA"),
                            ("AA+", "AA+"),
                            ("AA", "AA"),
                            ("AA-", "AA-"),
                            ("A+", "A+"),
                            ("A", "A"),
                            ("A-", "A-"),
                            ("BBB+", "BBB+"),
                            ("UNRATED", "UNRATED"),
                        ],
                        help_text="Rating value (e.g., AA (Stable), BBB+, etc.).",
                        max_length=10,
                    ),
                ),
                (
                    "valid_till",
                    models.DateField(
                        help_text="Expiration date of this credit rating."
                    ),
                ),
                (
                    "additional_rating",
                    models.CharField(
                        blank=True,
                        help_text="Optional remarks or additional rating comments.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "upload_letter",
                    models.FileField(
                        blank=True,
                        help_text="Encrypted uploaded PDF of the official credit rating letter.",
                        null=True,
                        upload_to="credit_ratings/letters/",
                    ),
                ),
                (
                    "reting_status",
                    models.BooleanField(
                        default=False,
                        help_text="True if the rating is active/valid; False if expired or invalid.",
                    ),
                ),
                (
                    "is_del",
                    models.SmallIntegerField(
                        default=0,
                        help_text="Logical delete flag — 0 = active, 1 = deleted.",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Linked company for which the rating is issued.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_ratings",
                        to="issuer_kyc.companyinformation",
                    ),
                ),
                (
                    "user_id_updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User/admin who last updated this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_rating_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "credit_rating_details",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FinancialDocument",
            fields=[
                (
                    "del_flag",
                    models.SmallIntegerField(default=0, help_text="Soft delete flag"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("document_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("GSTR_3B", "GSTR-3B"),
                            ("GSTR_9", "GSTR-9"),
                            ("ITR", "Income Tax Return"),
                            ("FINANCIAL_STATEMENT", "Audited Financial Statement"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "document_tag",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PROVISIONAL", "Provisional"),
                            ("AUDITED", "Audited"),
                        ],
                        max_length=20,
                    ),
                ),
                ("financial_year", models.CharField(max_length=9)),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("YEARLY", "Yearly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("period_start_date", models.DateField()),
                ("period_end_date", models.DateField()),
                ("period_code", models.CharField(blank=True, max_length=20, null=True)),
                ("version", models.SmallIntegerField(default=1)),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_path",
                    models.FileField(
                        blank=True,
                        max_length=500,
                        null=True,
                        upload_to=apps.bond_estimate.utils.financial_documents.financial_document_path.financial_document_upload_path,
                    ),
                ),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                (
                    "mime_type",
                    models.CharField(default="application/pdf", max_length=100),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "verification_source",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Verification"),
                            ("GST_PORTAL", "GST Portal API"),
                            ("INCOME_TAX_API", "Income Tax API"),
                            ("THIRD_PARTY_API", "Third Party Verification"),
                            ("MANUAL", "Manual Verification"),
                        ],
                        default="PENDING",
                        max_length=100,
                    ),
                ),
                (
                    "verification_reference_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "auditor_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("audit_report_date", models.DateField(blank=True, null=True)),
                (
                    "audit_firm_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="financial_documents",
                        to="issuer_kyc.companyinformation",
                    ),
                ),
                (
                    "user_id_updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "financial_documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FundPosition",
            fields=[
                (
                    "del_flag",
                    models.SmallIntegerField(default=0, help_text="Soft delete flag"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fund_position_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cash_balance_date", models.DateField(db_index=True)),
                ("bank_balance_date", models.DateField(db_index=True)),
                (
                    "cash_balance_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "bank_balance_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "application",
                    models.OneToOneField(
                        db_column="application_id",
                        help_text="Bond estimation application reference",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fund_position",
                        to="bond_estimate.bondestimationapplication",
                    ),
                ),
                (
                    "user_id_updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "fund_position",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PreliminaryBondRequirements",
            fields=[
                (
                    "del_flag",
                    models.SmallIntegerField(default=0, help_text="Soft delete flag"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "preliminarybond_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("issue_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "security_type",
                    models.CharField(
                        choices=[("Secured", "Secured"), ("Unsecured", "Unsecured")],
                        max_length=20,
                    ),
                ),
                (
                    "tenure",
                    models.DecimalField(
                        decimal_places=2, help_text="Tenure in years", max_digits=5
                    ),
                ),
                (
                    "preferred_roi",
                    models.DecimalField(
                        decimal_places=2, help_text="Preferred ROI %", max_digits=5
                    ),
                ),
                (
                    "coupon_rate",
                    models.DecimalField(
                        decimal_places=2, help_text="Coupon Rate %", max_digits=5
                    ),
                ),
                ("preferred_investor_categories", models.JSONField()),
                ("preferred_interest_payment_cycle", models.JSONField()),
                (
                    "application",
                    models.OneToOneField(
                        db_column="application_id",
                        help_text="Bond estimation application this preliminary requirement belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preliminary_bond_requirements",
                        to="bond_estimate.bondestimationapplication",
                    ),
                ),
                (
                    "user_id_updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "preliminary_bond_requirements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProfitabilityRatios",
            fields=[
                (
                    "del_flag",
                    models.SmallIntegerField(default=0, help_text="Soft delete flag"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ratio_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "net_profit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "net_worth",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "ebitda",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "debt_equity_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "current_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "quick_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "return_on_equity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "return_on_assets",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "dscr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Debt-Service Coverage Ratio",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "application",
                    models.OneToOneField(
                        db_column="application_id",
                        help_text="Bond estimation application this ratio set belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profitability_ratios",
                        to="bond_estimate.bondestimationapplication",
                    ),
                ),
                (
                    "user_id_updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "profitability_ratios",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TempUploadedFile",
            fields=[
                (
                    "temp_file_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_path", models.TextField()),
                ("original_name", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="bondestimationapplication",
            index=models.Index(
                fields=["company", "status"], name="bond_estima_company_510c94_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bondestimationapplication",
            index=models.Index(
                fields=["user", "created_at"], name="bond_estima_user_id_7d64c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="borrowingdetails",
            index=models.Index(
                fields=["application", "is_del"], name="idx_borrow_app_active"
            ),
        ),
        migrations.AddIndex(
            model_name="borrowingdetails",
            index=models.Index(fields=["borrowing_type"], name="idx_borrow_type"),
        ),
        migrations.AddIndex(
            model_name="borrowingdetails",
            index=models.Index(fields=["created_at"], name="idx_borrow_created"),
        ),
        migrations.AddIndex(
            model_name="borrowingdetails",
            index=models.Index(
                fields=["is_del", "application", "-created_at"],
                name="idx_borrow_app_date",
            ),
        ),
        migrations.AddIndex(
            model_name="capitaldetails",
            index=models.Index(fields=["application"], name="idx_capital_app"),
        ),
        migrations.AddConstraint(
            model_name="capitaldetails",
            constraint=models.UniqueConstraint(
                fields=("application",), name="unique_capital_details_per_application"
            ),
        ),
        migrations.AddIndex(
            model_name="collateralassetverification",
            index=models.Index(
                fields=["application"], name="idx_collateral_application"
            ),
        ),
        migrations.AddIndex(
            model_name="collateralassetverification",
            index=models.Index(fields=["collateral_type"], name="idx_collateral_type"),
        ),
        migrations.AddIndex(
            model_name="collateralassetverification",
            index=models.Index(fields=["charge_type"], name="idx_collateral_charge"),
        ),
        migrations.AddIndex(
            model_name="collateralassetverification",
            index=models.Index(
                fields=["ownership_type"], name="idx_collateral_ownership"
            ),
        ),
        migrations.AddIndex(
            model_name="collateralassetverification",
            index=models.Index(fields=["created_at"], name="idx_collateral_created_at"),
        ),
        migrations.AddConstraint(
            model_name="collateralassetverification",
            constraint=models.UniqueConstraint(
                fields=("application",), name="unique_collateral_per_application"
            ),
        ),
        migrations.AddIndex(
            model_name="creditratingdetails",
            index=models.Index(
                fields=["company"], name="credit_rati_company_6be55e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creditratingdetails",
            index=models.Index(fields=["agency"], name="credit_rati_agency_bae902_idx"),
        ),
        migrations.AddIndex(
            model_name="creditratingdetails",
            index=models.Index(fields=["rating"], name="credit_rati_rating_05fcb4_idx"),
        ),
        migrations.AddIndex(
            model_name="creditratingdetails",
            index=models.Index(
                fields=["valid_till"], name="credit_rati_valid_t_6e27e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creditratingdetails",
            index=models.Index(
                fields=["reting_status"], name="credit_rati_reting__b43aac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialdocument",
            index=models.Index(
                fields=["company", "document_type"],
                name="financial_d_company_240d66_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="financialdocument",
            index=models.Index(
                fields=["financial_year", "document_tag"],
                name="financial_d_financi_afade7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="financialdocument",
            index=models.Index(
                fields=["period_start_date", "period_end_date"],
                name="financial_d_period__b06a1b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="financialdocument",
            index=models.Index(
                fields=["is_verified", "verification_source"],
                name="financial_d_is_veri_8a01fd_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="financialdocument",
            unique_together={
                (
                    "company",
                    "document_type",
                    "period_start_date",
                    "period_end_date",
                    "document_tag",
                    "version",
                )
            },
        ),
        migrations.AddIndex(
            model_name="fundposition",
            index=models.Index(fields=["application"], name="idx_fund_pos_app"),
        ),
        migrations.AddIndex(
            model_name="fundposition",
            index=models.Index(
                fields=["cash_balance_date"], name="idx_fund_pos_cash_dt"
            ),
        ),
        migrations.AddIndex(
            model_name="fundposition",
            index=models.Index(
                fields=["bank_balance_date"], name="idx_fund_pos_bank_dt"
            ),
        ),
        migrations.AddIndex(
            model_name="fundposition",
            index=models.Index(
                fields=["user_id_updated_by", "created_at"],
                name="idx_fund_pos_user_created",
            ),
        ),
        migrations.AddIndex(
            model_name="fundposition",
            index=models.Index(
                fields=["del_flag", "application", "created_at"],
                name="idx_fund_pos_list",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundposition",
            constraint=models.UniqueConstraint(
                fields=("application",), name="unique_fund_position_application"
            ),
        ),
        migrations.AddConstraint(
            model_name="fundposition",
            constraint=models.CheckConstraint(
                condition=models.Q(("cash_balance_amount__gte", 0)),
                name="check_cash_balance_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundposition",
            constraint=models.CheckConstraint(
                condition=models.Q(("bank_balance_amount__gte", 0)),
                name="check_bank_balance_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundposition",
            constraint=models.CheckConstraint(
                condition=models.Q(("del_flag__in", [0, 1])),
                name="check_del_flag_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="preliminarybondrequirements",
            index=models.Index(fields=["application"], name="idx_prebond_application"),
        ),
        migrations.AddIndex(
            model_name="preliminarybondrequirements",
            index=models.Index(
                fields=["security_type"], name="idx_prebond_security_type"
            ),
        ),
        migrations.AddIndex(
            model_name="preliminarybondrequirements",
            index=models.Index(
                fields=["issue_amount"], name="idx_prebond_issue_amount"
            ),
        ),
        migrations.AddIndex(
            model_name="preliminarybondrequirements",
            index=models.Index(fields=["coupon_rate"], name="idx_prebond_coupon_rate"),
        ),
        migrations.AddIndex(
            model_name="preliminarybondrequirements",
            index=models.Index(fields=["created_at"], name="idx_prebond_created_at"),
        ),
        migrations.AddConstraint(
            model_name="preliminarybondrequirements",
            constraint=models.UniqueConstraint(
                fields=("application",), name="unique_prelim_req_per_application"
            ),
        ),
        migrations.AddIndex(
            model_name="profitabilityratios",
            index=models.Index(
                fields=["application"], name="idx_profitability_application"
            ),
        ),
        migrations.AddConstraint(
            model_name="profitabilityratios",
            constraint=models.UniqueConstraint(
                fields=("application",), name="unique_profitability_per_application"
            ),
        ),
    ]
