# Generated by Django 5.2.6 on 2025-11-12 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond_estimate', '0001_initial'),
        ('issuer_kyc', '0002_financialdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondestimationapplication',
            name='company',
            field=models.ForeignKey(help_text='Linked company for which the rating is issued.', on_delete=django.db.models.deletion.CASCADE, related_name='bond_estimations', to='issuer_kyc.companyinformation'),
        ),
        migrations.CreateModel(
            name='CapitalDetails',
            fields=[
                ('del_flag', models.SmallIntegerField(default=0, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capital_detail_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('share_capital', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reserves_surplus', models.DecimalField(decimal_places=2, max_digits=18)),
                ('net_worth', models.DecimalField(decimal_places=2, max_digits=18)),
                ('company', models.ForeignKey(help_text='Linked company for which the rating is issued.', on_delete=django.db.models.deletion.CASCADE, related_name='captial_ratings', to='issuer_kyc.companyinformation')),
                ('user_id_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'capital_details',
                'indexes': [models.Index(fields=['company'], name='capital_det_company_83cf62_idx')],
            },
        ),
        migrations.CreateModel(
            name='CreditRatingDetails',
            fields=[
                ('del_flag', models.SmallIntegerField(default=0, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_rating_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('agency', models.CharField(choices=[('CRISIL', 'CRISIL'), ('ICRA', 'ICRA'), ('CARE', 'CARE Ratings'), ('IND-RA', 'India Ratings & Research'), ('BWR', 'Brickwork Ratings'), ('ACUITE', 'Acuité Ratings')], help_text='Credit rating agency (e.g., CRISIL, ICRA, CARE, etc.).', max_length=50)),
                ('rating', models.CharField(choices=[('AAA', 'AAA'), ('AA+', 'AA+'), ('AA', 'AA'), ('AA-', 'AA-'), ('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('BBB+', 'BBB+'), ('UNRATED', 'UNRATED')], help_text='Rating value (e.g., AA (Stable), BBB+, etc.).', max_length=10)),
                ('valid_till', models.DateField(help_text='Expiration date of this credit rating.')),
                ('additional_rating', models.CharField(blank=True, help_text='Optional remarks or additional rating comments.', max_length=255, null=True)),
                ('upload_letter', models.FileField(blank=True, help_text='Encrypted uploaded PDF of the official credit rating letter.', null=True, upload_to='credit_ratings/letters/')),
                ('reting_status', models.BooleanField(default=False, help_text='True if the rating is active/valid; False if expired or invalid.')),
                ('is_del', models.SmallIntegerField(default=0, help_text='Logical delete flag — 0 = active, 1 = deleted.')),
                ('company', models.ForeignKey(help_text='Linked company for which the rating is issued.', on_delete=django.db.models.deletion.CASCADE, related_name='credit_ratings', to='issuer_kyc.companyinformation')),
                ('user_id_updated_by', models.ForeignKey(blank=True, help_text='User/admin who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_rating_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credit_rating_details',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company'], name='credit_rati_company_6be55e_idx'), models.Index(fields=['agency'], name='credit_rati_agency_bae902_idx'), models.Index(fields=['rating'], name='credit_rati_rating_05fcb4_idx'), models.Index(fields=['valid_till'], name='credit_rati_valid_t_6e27e3_idx'), models.Index(fields=['reting_status'], name='credit_rati_reting__b43aac_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'agency', 'rating'), name='unique_company_agency_rating')],
            },
        ),
    ]
