# Generated by Django 5.2.6 on 2025-11-13 05:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond_estimate', '0002_alter_bondestimationapplication_company_and_more'),
        ('issuer_kyc', '0002_financialdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundPosition',
            fields=[
                ('del_flag', models.SmallIntegerField(default=0, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund_position_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Primary key (UUID)', primary_key=True, serialize=False)),
                ('cash_balance_date', models.DateField(db_index=True, help_text='Date of cash balance')),
                ('bank_balance_date', models.DateField(db_index=True, help_text='Date of bank balance')),
                ('cash_balance_amount', models.DecimalField(decimal_places=2, help_text='Cash balance amount', max_digits=15)),
                ('bank_balance_amount', models.DecimalField(decimal_places=2, help_text='Bank balance amount', max_digits=15)),
                ('remarks', models.TextField(blank=True, help_text='Optional remarks', null=True)),
                ('company', models.ForeignKey(db_column='company_id', help_text='Reference to company', on_delete=django.db.models.deletion.CASCADE, related_name='fund_positions', to='issuer_kyc.companyinformation')),
                ('user_id_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fund_position',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'del_flag'], name='idx_fund_pos_comp_del'), models.Index(fields=['company', 'cash_balance_date'], name='idx_fund_pos_comp_cash_dt'), models.Index(fields=['company', 'bank_balance_date'], name='idx_fund_pos_comp_bank_dt'), models.Index(fields=['user_id_updated_by', 'created_at'], name='idx_fund_pos_user_created'), models.Index(fields=['company', 'del_flag', 'created_at'], name='idx_fund_pos_list')],
                'constraints': [models.CheckConstraint(condition=models.Q(('cash_balance_amount__gte', 0)), name='check_cash_balance_positive'), models.CheckConstraint(condition=models.Q(('bank_balance_amount__gte', 0)), name='check_bank_balance_positive'), models.CheckConstraint(condition=models.Q(('del_flag__in', [0, 1])), name='check_del_flag_valid')],
            },
        ),
    ]
