# Generated by Django 5.2.6 on 2025-11-14 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond_estimate', '0003_fundposition'),
        ('issuer_kyc', '0002_financialdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitabilityRatios',
            fields=[
                ('del_flag', models.SmallIntegerField(default=0, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ratio_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('net_profit', models.DecimalField(blank=True, decimal_places=2, help_text='Net profit amount', max_digits=18, null=True)),
                ('net_worth', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('ebitda', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('debt_equity_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('current_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('quick_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('return_on_equity', models.DecimalField(blank=True, decimal_places=2, help_text='ROE percentage', max_digits=5, null=True)),
                ('return_on_assets', models.DecimalField(blank=True, decimal_places=2, help_text='ROA percentage', max_digits=5, null=True)),
                ('dscr', models.DecimalField(blank=True, decimal_places=4, help_text='Debt-Service Coverage Ratio', max_digits=10, null=True)),
                ('company', models.OneToOneField(blank=True, help_text='Company for which the profitability and ratios are recorded.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profitability_ratios', to='issuer_kyc.companyinformation')),
                ('user_id_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profitability_ratios',
                'indexes': [models.Index(fields=['company'], name='profitabili_company_ca2879_idx')],
            },
        ),
    ]
