# Generated by Django 5.2.6 on 2025-11-14 12:08

import apps.bond_estimate.models.CollateralAssetVerificationModel
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bond_estimate", "0003_fundposition"),
        ("issuer_kyc", "0002_financialdocument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollateralAssetVerification",
            fields=[
                (
                    "del_flag",
                    models.SmallIntegerField(default=0, help_text="Soft delete flag"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "collateral_type",
                    models.CharField(
                        choices=[
                            ("Land", "Land"),
                            ("Equipment", "Equipment"),
                            ("Receivables", "Receivables"),
                            ("Shares", "Shares"),
                            ("Project Assets", "Project Assets"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "charge_type",
                    models.CharField(
                        choices=[
                            ("First Charge", "First Charge"),
                            ("Second Charge", "Second Charge"),
                            ("Exclusive Charge", "Exclusive Charge"),
                            ("Pari Passu Charge", "Pari Passu Charge"),
                            ("Subservient Charge", "Subservient Charge"),
                        ],
                        max_length=50,
                    ),
                ),
                ("asset_description", models.TextField()),
                (
                    "estimated_value",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("valuation_date", models.DateField()),
                (
                    "security_document_file",
                    models.FileField(
                        blank=True,
                        max_length=500,
                        null=True,
                        upload_to=apps.bond_estimate.models.CollateralAssetVerificationModel.security_document_upload_path,
                    ),
                ),
                (
                    "security_document_ref",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("trust_name", models.CharField(max_length=255)),
                (
                    "ownership_type",
                    models.CharField(
                        choices=[
                            ("Owned", "Owned"),
                            ("Leased", "Leased"),
                            ("Pledged", "Pledged"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "asset_cover_certificate",
                    models.FileField(
                        blank=True,
                        max_length=500,
                        null=True,
                        upload_to=apps.bond_estimate.models.CollateralAssetVerificationModel.asset_cover_certificate_upload_path,
                    ),
                ),
                (
                    "valuation_report",
                    models.FileField(
                        blank=True,
                        max_length=500,
                        null=True,
                        upload_to=apps.bond_estimate.models.CollateralAssetVerificationModel.valuation_report_upload_path,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collateral_assets",
                        to="issuer_kyc.companyinformation",
                    ),
                ),
                (
                    "user_id_updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "collateral_asset_verification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "del_flag"],
                        name="collateral__company_08769d_idx",
                    ),
                    models.Index(
                        fields=["collateral_type"],
                        name="collateral__collate_ffe471_idx",
                    ),
                    models.Index(
                        fields=["charge_type"], name="collateral__charge__8b907f_idx"
                    ),
                    models.Index(
                        fields=["ownership_type"], name="collateral__ownersh_097a4f_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="collateral__created_4abfe6_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PreliminaryBondRequirements",
            fields=[
                (
                    "del_flag",
                    models.SmallIntegerField(default=0, help_text="Soft delete flag"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("issue_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "security_type",
                    models.CharField(
                        choices=[("Secured", "Secured"), ("Unsecured", "Unsecured")],
                        max_length=20,
                    ),
                ),
                (
                    "tenure",
                    models.DecimalField(
                        decimal_places=2, help_text="Tenure in years", max_digits=5
                    ),
                ),
                (
                    "preferred_roi",
                    models.DecimalField(
                        decimal_places=2, help_text="Preferred ROI %", max_digits=5
                    ),
                ),
                ("preferred_investor_categories", models.JSONField()),
                ("preferred_interest_payment_cycle", models.JSONField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preliminary_bond_requirements",
                        to="issuer_kyc.companyinformation",
                    ),
                ),
                (
                    "user_id_updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "preliminary_bond_requirements",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "del_flag"],
                        name="preliminary_company_b58759_idx",
                    ),
                    models.Index(
                        fields=["security_type"], name="preliminary_securit_d00390_idx"
                    ),
                    models.Index(
                        fields=["issue_amount"], name="preliminary_issue_a_dd6396_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="preliminary_created_0bd5e8_idx"
                    ),
                ],
            },
        ),
    ]
