# Generated by Django 5.2.6 on 2025-11-15 06:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bond_estimate", "0004_collateralassetverification_and_more"),
        ("issuer_kyc", "0002_financialdocument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="preliminarybondrequirements",
            name="coupon_rate",
            field=models.DecimalField(
                decimal_places=2, default=0.0, help_text="Coupon Rate %", max_digits=5
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="preliminarybondrequirements",
            index=models.Index(
                fields=["coupon_rate"], name="preliminary_coupon__d522e6_idx"
            ),
        ),
    ]
