# Generated by Django 5.2.6 on 2025-11-15 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bond_estimate', '0004_collateralassetverification_and_more'),
        ('bond_estimate', '0004_profitabilityratios'),
    ]

    operations = [
    ]
