# Generated by Django 5.2.6 on 2025-11-16 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bond_estimate', '0005_merge_20251115_0539'),
    
    ]

    operations = [
    ]
