# Generated by Django 5.2.6 on 2025-11-16 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond_estimate', '0006_merge_20251116_1402'),
        ('issuer_kyc', '0003_alter_companyinformation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profitabilityratios',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company for which the profitability and ratios are recorded.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profitability_ratios', to='issuer_kyc.companyinformation'),
        ),
    ]
