# Generated by Django 5.2.6 on 2025-11-17 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bond_estimate", "0005_preliminarybondrequirements_coupon_rate_and_more"),
        ("bond_estimate", "0007_alter_profitabilityratios_company"),
    ]

    operations = []
