# Generated by Django 5.2.6 on 2025-11-17 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bond_estimate", "0008_merge_20251117_1548"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="creditratingdetails",
            name="unique_company_agency_rating",
        ),
    ]
