# Generated by Django 5.2.6 on 2025-11-19 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bond_estimate', '0008_merge_20251117_1046'),
        ('bond_estimate', '0009_remove_creditratingdetails_unique_company_agency_rating'),
    ]

    operations = [
    ]
