# Generated by Django 5.2.6 on 2025-11-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bond_estimate', '0010_merge_20251119_0511'),
        ('bond_estimate', '0010_merge_20251119_1644'),
    ]

    operations = [
    ]
